FROM node:latest

RUN npm config set registry https://registry.npm.taobao.org

ENV FRONTEND=/opt/frontend

WORKDIR $FRONTEND

COPY package.json $FRONTEND
RUN npm install

COPY . $FRONTEND
RUN npm run build

COPY package.json FRONTEND