name: GitHub Actions Demo
on: 
  push:
    branch:
      - main
      - ci/frontend
  pull_request:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
